### DISCUSSION TITLE
Adding Directive to columnTemplate

### DISCUSSION THREAD

**Discussion by Thoemmy** [revolist/revogrid#480] [General]
Currently i want to add from PrimeNG the tooltip component to the Column Headers, so that if a user hovers over the column text which can be displayed with ellipsis he will receive a tooltip.

Ive tried following:

1. implement custom tooltip, to test the own tooltip, which is also not working unfortunately
```typescript
      columnTemplate: (createElement: HyperFunc<VNode>, props: ColumnTemplateProp) => {
        return createElement(
          'div',
          {
            class: 'tooltip',
            innerHTML: props.name,
          },
          createElement('span', { class: 'tooltiptext' }, props.name)
        );
      },
```

the related css:
```css
.tooltip {
  position: relative;
  display: inline-block;
  border-bottom: 1px dotted black;
}

.tooltip .tooltiptext {
  visibility: hidden;
  width: 120px;
  background-color: #555;
  color: #fff;
  text-align: center;
  border-radius: 6px;
  padding: 5px 0;
  position: absolute;
  z-index: 1;
  bottom: 125%;
  left: 50%;
  margin-left: -60px;
  opacity: 0;
  transition: opacity 0.3s;
}

.tooltip .tooltiptext::after {
  content: '';
  position: absolute;
  top: 100%;
  left: 50%;
  margin-left: -5px;
  border-width: 5px;
  border-style: solid;
  border-color: #555 transparent transparent transparent;
}

.tooltip:hover .tooltiptext {
  visibility: visible;
  opacity: 1;
}

```

2. implement directive of PrimeNG Tooltip Module
```typescript
      columnTemplate: (createElement: HyperFunc<VNode>, props: ColumnTemplateProp) => {
        return createElement(
          'span',
          {
            pTooltip: props.name,
          },
          props.name
        );
      },
```
PrimeNG example
https://codesandbox.io/p/sandbox/icon-of-rowdrag-is-not-displayed-properly-in-angular-using-any-material-theme-forked-q9ly99?file=%2Fsrc%2Findex.html

Is there a way to get this working?
