### ISSUE TITLE
Grid size based on content

### ISSUE THREAD

**Issue by Techn1x** [revolist/revogrid#600]
Have been implementing this library to help create a grid for importing records, I noticed the container has a fixed / static min-height 300px by default (as the guides mention) as well as a 100% width

![Screenshot 2024-10-14 at 1 57 56 pm](https://github.com/user-attachments/assets/23ba208f-3571-41ee-af4f-d5e2879cd4db)

I wanted to share a slightly different approach to the grid sizing, where instead of the content growing to meet the fixed container that never changes, the container grows with the content (up to a maximum size, if desired)

The width is easily taken care of with `width: max-content` - it will even let you expand that last column rightwards if needed
```html
<revo-grid class="w-max" />
```

![Screenshot 2024-10-14 at 2 02 05 pm](https://github.com/user-attachments/assets/f86265d8-7932-4d56-bb79-bbe09f36c4d0)

The height needs some more complicated CSS to undo all the cascading "height: 100%" values everywhere

```html
<revo-grid class="w-max revogrid-autoheight" />
```

```css
.revogrid-autoheight {
  min-height: unset;
}

.revogrid-autoheight .main-viewport,
.revogrid-autoheight .rowHeaders,
.revogrid-autoheight .rgCol {
  height: unset;
}

/* this is optional, if you want scrolling or not */
.revogrid-autoheight .inner-content-table,
.revogrid-autoheight revogr-scroll-virtual.vertical {
  max-height: 32rem;
}
```

https://github.com/user-attachments/assets/717dea40-cc56-4373-abc7-39c80c4439be

This of works in my simple scenario, but likely breaks things for more complicated grid's using features that I am not.

Is this something that should be implemented, maybe as a different theme or plugin or layout option for the grid?
