### ISSUE TITLE
Theming select menu and filters

### ISSUE THREAD

**Issue by MattTheCuber** [revolist/revogrid#627]
This issue is for https://github.com/revolist/revogrid-column-select and this repo.

Currently, in dark theme, select menus and filtering look quite poor. You can see this by going to the official demo: https://rv-grid.com/demo/

![image](https://github.com/user-attachments/assets/e9aa9a9c-206c-4f2b-8daa-eddd78adff7d)

Is there a easy way to style these depending on the theme? Currently we are using Vuetify and using the theme variables like this:

```css
revogr-filter-panel {
    background-color: rgb(var(--v-theme-surface-light)) !important;
}
revogr-filter-panel > label {
    color: rgba(var(--v-theme-on-background), var(--v-high-emphasis-opacity));
}
.select-css {
    background-color: rgb(var(--v-theme-surface));
    background-image: none;
    color: rgba(var(--v-theme-on-background), var(--v-high-emphasis-opacity));
    border-color: rgba(var(--v-border-color), var(--v-border-opacity));
}
.select-css:focus {
    color: rgba(var(--v-theme-on-background), var(--v-high-emphasis-opacity));
}
revogr-filter-panel input[type='text'] {
    background-color: rgb(var(--v-theme-surface)) !important;
}
#revo-button-reset {
    color: rgba(var(--v-theme-on-surface), var(--v-high-emphasis-opacity));
}
.and-or-button {
    color: rgba(var(--v-theme-on-surface), var(--v-high-emphasis-opacity)) !important;
}
```

However, we are unable to themed styles the dropdown because it is stuck in the root body and not instead of any Vuetify containers.

**Comment by ConnorNoddin** [comment]
Bump. I have also encountered this issue in the past

**Comment by m2a2x** [comment]
hi @MattTheCuber 
there are some options for you:

1. For dropdown you can add to column level appendTo: 'class name'
2. filter panel is inside of the dom, can be colorized the way you described

By the way you can use vitepress components inside of the grid too, we've built a lot of applications this way.

**Comment by MattTheCuber** [comment]
Hello @m2a2x,

Thank you for the help. I tried adding the `appendTo` keyword to the column properties with a root div's class (`appendTo: 'v-application'`). This put the div nested inside of the cell instead of the root div, resulting in fixing the styling but positioning the dropdown in an undesired location.

Also, can you describe how the filter panel was updated to allow theming?

**Comment by m2a2x** [comment]
Hi @MattTheCuber 
1. I think only in the latest version of dropdown is should work, also it should be a selector: '.v-application'
2. Panel is inside of the grid I suppose hence you can reach it same as grid. Also in the latest release this would be with black theme support.

**Comment by MattTheCuber** [comment]
That worked, thank you!

FYI, here is the CSS I used if anyone else wants to theme these components:

```css
.select-css {
    background-color: rgb(var(--v-theme-surface));
    background-image: none;
    color: rgba(var(--v-theme-on-background), var(--v-high-emphasis-opacity));
    border-color: rgba(var(--v-border-color), var(--v-border-opacity));
}
.select-css:focus {
    color: rgba(var(--v-theme-on-background), var(--v-high-emphasis-opacity));
}
revogr-filter-panel input[type='text'] {
    color: rgba(var(--v-theme-on-background), var(--v-high-emphasis-opacity)) !important;
    background-color: rgb(var(--v-theme-surface-light)) !important;
}

.revo-dropdown-list .dropdown-inner {
    color: rgba(var(--v-theme-on-surface), var(--v-high-emphasis-opacity)) !important;
    background-color: rgb(var(--v-theme-surface)) !important;
}
```
